(define-module (gunit packages bolt-launcher)
  #:use-module ((guix licenses)
                #:prefix license:)
  #:use-module (guix gexp)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:use-module (guix git-download)
  #:use-module (guix utils)
  #:use-module (gnu packages)
  #:use-module (gnu packages admin)
  #:use-module (gnu packages algebra)
  #:use-module (gnu packages assembly)
  #:use-module (gnu packages astronomy)
  #:use-module (gnu packages audio)
  #:use-module (gnu packages avahi)
  #:use-module (gnu packages autotools)
  #:use-module (gnu packages base)
  #:use-module (gnu packages backup)
  #:use-module (gnu packages bash)
  #:use-module (gnu packages boost)
  #:use-module (gnu packages check)
  #:use-module (gnu packages chromium)
  #:use-module (gnu packages cmake)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages cups)
  #:use-module (gnu packages curl)
  #:use-module (gnu packages databases)
  #:use-module (gnu packages documentation)
  #:use-module (gnu packages elf)
  #:use-module (gnu packages engineering)
  #:use-module (gnu packages file)
  #:use-module (gnu packages fltk)
  #:use-module (gnu packages freedesktop)
  #:use-module (gnu packages fontutils)
  #:use-module (gnu packages fonts)
  #:use-module (gnu packages gawk)
  #:use-module (gnu packages gcc)
  #:use-module (gnu packages gd)
  #:use-module (gnu packages geo)
  #:use-module (gnu packages gettext)
  #:use-module (gnu packages ghostscript)
  #:use-module (gnu packages gl)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages gnome)
  #:use-module (gnu packages golang)
  #:use-module (gnu packages golang-xyz)
  #:use-module (gnu packages gps)
  #:use-module (gnu packages graphics)
  #:use-module (gnu packages graphviz)
  #:use-module (gnu packages gstreamer)
  #:use-module (gnu packages gtk)
  #:use-module (gnu packages image)
  #:use-module (gnu packages image-processing)
  #:use-module (gnu packages javascript)
  #:use-module (gnu packages jemalloc)
  #:use-module (gnu packages libedit)
  #:use-module (gnu packages libusb)
  #:use-module (gnu packages libbsd)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages lsof)
  #:use-module (gnu packages llvm)
  #:use-module (gnu packages logging)
  #:use-module (gnu packages lua)
  #:use-module (gnu packages man)
  #:use-module (gnu packages maths)
  #:use-module (gnu packages mp3)
  #:use-module (gnu packages multiprecision)
  #:use-module (gnu packages ncurses)
  #:use-module (gnu packages networking)
  #:use-module (gnu packages nss)
  #:use-module (gnu packages openstack)
  #:use-module (gnu packages pciutils)
  #:use-module (gnu packages perl)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages popt)
  #:use-module (gnu packages pulseaudio)
  #:use-module (gnu packages protobuf)
  #:use-module (gnu packages pretty-print)
  #:use-module (gnu packages python)
  #:use-module (gnu packages python-build)
  #:use-module (gnu packages onc-rpc)
  #:use-module (gnu packages python-check)
  #:use-module (gnu packages python-science)
  #:use-module (gnu packages python-web)
  #:use-module (gnu packages python-xyz)
  #:use-module (gnu packages qt)
  #:use-module (gnu packages readline)
  #:use-module (gnu packages ruby)
  #:use-module (gnu packages sdl)
  #:use-module (gnu packages serialization)
  #:use-module (gnu packages sphinx)
  #:use-module (gnu packages sqlite)
  #:use-module (gnu packages swig)
  #:use-module (gnu packages tcl)
  #:use-module (gnu packages tex)
  #:use-module (gnu packages texinfo)
  #:use-module (gnu packages tls)
  #:use-module (gnu packages toolkits)
  #:use-module (gnu packages vulkan)
  #:use-module (gnu packages video)
  #:use-module (gnu packages web)
  #:use-module (gnu packages icu4c)
  #:use-module (gnu packages wxwidgets)
  #:use-module (gnu packages xiph)
  #:use-module (gnu packages xdisorg)
  #:use-module (gnu packages xml)
  #:use-module (gnu packages xorg)
  #:use-module (gnu packages version-control)
  #:use-module (guix build-system cmake)
  #:use-module (guix build-system glib-or-gtk)
  #:use-module (guix build-system gnu)
  #:use-module (guix build-system go)
  #:use-module (guix build-system pyproject)
  #:use-module (guix build-system python)
  #:use-module (guix build-system qt)
  #:use-module (guix build utils)
  #:use-module (guix build gnu-build-system)
  #:use-module (guix base16)
  #:use-module (gunit packages chromium)
  #:use-module (nongnu packages editors)
  #:use-module (nonguix build-system binary)
  #:use-module (nonguix multiarch-container)
  #:use-module (nonguix utils))

(define bolt-launcher-client
  (package
    (name "bolt-launcher")
    (version "0.21.0")
    (source
     (origin
       (method git-fetch)
       (uri (git-reference
             (url "https://codeberg.org/Adamcake/Bolt")
             (commit "7b784af90e80b286200f7359f2fced6d8fb6e40e")
             (recursive? #t)))
       (sha256
        (base32 "0jirsr3i2lwq4qz66gc0ykk3fqp0hm5x63qwh9xgwzay5i84l0j1"))))
    (build-system cmake-build-system)

    (inputs (list chromium-embedded-framework
                  eudev
                  libarchive
                  glib
                  glibc
                  gtk
                  xdg-utils
                  libxshmfence
                  hicolor-icon-theme
                  nss
                  fmt
                  spng
                  mesa
                  vulkan-loader
                  wayland))
    (arguments
     (list
      #:tests? #f
      #:configure-flags
      #~(list
         ;; Can probably clean this up
         (string-append "-D " "CMAKE_INSTALL_PREFIX="
                        (assoc-ref %outputs "out"))
         ;;(string-append "-D " "BOLT_DEV_SHOW_DEVTOOLS=" "1")
         (string-append "-DBOLT_BINDIR=" "./bin")
         (string-append "-DBOLT_SHAREDIR=" "./share")
         (string-append "-DBOLT_LIBDIR=" "./lib")
         (string-append "-DCEF_DIR="
                        (assoc-ref %build-inputs "chromium-embedded-framework"))
         (string-append "-DCEF_ROOT="
                        (assoc-ref %build-inputs "chromium-embedded-framework"))
         (string-append "-DBOLT_CEF_RESOURCEDIR_OVERRIDE="
                        (assoc-ref %build-inputs "chromium-embedded-framework")
                        "/share/cef")
         (string-append "-DBOLT_LIBCEF_DIRECTORY="
                        (assoc-ref %build-inputs "chromium-embedded-framework")
                        "/lib")
         (string-append "-DBOLT_CEF_INCLUDEPATH="
                        (assoc-ref %build-inputs "chromium-embedded-framework"))
         (string-append "-DBOLT_CEF_DLLWRAPPER="
                        (assoc-ref %build-inputs "chromium-embedded-framework")
                        "/lib/libcef_dll_wrapper.a")
         "-D BOLT_META_NAME=bolt-launcher"
         "-D BOLT_SKIP_LIBRARIES=1")
      #:phases
      #~(modify-phases %standard-phases
          (add-after 'install 'link-cef-and-wrap
            (lambda* (#:key inputs outputs #:allow-other-keys)
              (let* ((out (assoc-ref outputs "out"))
                     (opt-dir (string-append out "/opt/bolt-launcher"))
                     (bin-dir (string-append out "/bin"))
                     (cef (assoc-ref inputs "chromium-embedded-framework"))
                     (mesa (assoc-ref inputs "mesa"))
                     (vulkan (assoc-ref inputs "vulkan-loader"))
                     (gtk (assoc-ref inputs "gtk"))
                     (udev (assoc-ref inputs "eudev"))
                     (nss (assoc-ref inputs "nss"))
                     (xdg (assoc-ref inputs "xdg-utils")))
                
                (for-each (lambda (file)
                            (symlink (string-append cef "/share/cef/" file)
                                     (string-append opt-dir "/" file)))
                          '("chrome_100_percent.pak" "chrome_200_percent.pak"
                            "resources.pak" "icudtl.dat"
                            "v8_context_snapshot.bin"))

                (symlink (string-append cef "/share/cef/locales")
                         (string-append opt-dir "/locales"))
                ;;  TODO: should dig into this more so CEF can behave how it expects to
                ;;                (symlink (string-append mesa "/lib/libGLESv2.so.2")
                ;;                       (string-append opt-dir "/libGLESv2.so"))
                (symlink (string-append mesa "/lib/libEGL.so.1")
                         (string-append opt-dir "/libEGL.so"))
                (symlink (string-append mesa "/lib/libGL.so.1")
                         (string-append opt-dir "/libGL.so"))
                (symlink (string-append cef "/lib/libcef.so")
                         (string-append opt-dir "/libcef.so"))

                (mkdir-p bin-dir)
                (rename-file (string-append opt-dir "/bolt")
                             (string-append bin-dir "/bolt"))

                (wrap-program (string-append bin-dir "/bolt")
                  `("LD_LIBRARY_PATH" ":" prefix
                    (,(string-append opt-dir) ,(string-append mesa "/lib")
                     ,(string-append vulkan "/lib")
                     ,(string-append udev "/lib")
                     ,(string-append nss "/lib/nss")))
                  `("XDG_DATA_DIRS" ":" prefix
                    (,(string-append gtk "/share")))
                  `("PATH" ":" prefix
                    (,(string-append xdg "/bin")))
                  `("LD_PRELOAD" ":" prefix
                    (,(string-append mesa "/lib/libGL.so.1") ,(string-append
                                                               mesa
                                                               "/lib/libEGL.so.1")
                     ,(string-append mesa "/lib/libGLESv2.so.2")
                     ,(string-append vulkan "/lib/libvulkan.so.1"))))))))))
    (native-inputs (list cmake pkg-config git wayland))
    (synopsis
     "An alternative third-party open-source launcher for RuneScape or Old School RuneScape.")
    (home-page "https://bolt.adamcake.com/")
    (description
     "Free open-source third-party implementation of the Jagex Launcher.")
    (license license:agpl3)))

(define bolt-launcher-libs
  `(("at-spi2-core" ,at-spi2-core)
    ("bash" ,bash)
    ("cairo" ,cairo)
    ("coreutils" ,coreutils)
    ("diffutils" ,diffutils)
    ("dbus-glib" ,dbus-glib)
    ("elfutils" ,elfutils)
    ("eudev" ,eudev)
    ("expat" ,expat)
    ("fontconfig" ,fontconfig)
    ("file" ,file)
    ("find" ,findutils)
    ("fmt" ,fmt)
    ("font-google-noto" ,font-google-noto)
    ("font-google-noto-emoji" ,font-google-noto-emoji)
    ("font-google-noto-sans-cjk" ,font-google-noto-sans-cjk)
    ("font-google-noto-serif-cjk" ,font-google-noto-serif-cjk)
    ("freetype" ,freetype)
    ("bzip2" ,bzip2)
    ("curl" ,curl)
    ("libxtst" ,libxtst)
    ("libxscrnsaver" ,libxscrnsaver)
    ("gawk" ,gawk)
    ("gdk-pixbuf" ,gdk-pixbuf)
    ("gcc:lib" ,gcc-14 "lib")
    ("glib" ,glib)
    ("glibc" ,glibc)
    ("grep" ,grep)
    ("gtk+" ,gtk+)
    ("gtk" ,gtk+-2)
    ("libbsd" ,libbsd)
    ("libcap" ,libcap)
    ("libdrm" ,libdrm)
    ("libglvnd" ,libglvnd)
    ("libusb" ,libusb)
    ("libsm" ,libsm)
    ("libxcb" ,libxcb)
    ("libxcomposite" ,libxcomposite)
    ("libxext" ,libxext)
    ("libxkbcommon" ,libxkbcommon)
    ("libva" ,libva)
    ("libvdpau" ,libvdpau)
    ("libvdpau-va-gl" ,libvdpau-va-gl)
    ("libx11" ,libx11)
    ("libxdamage" ,libxdamage)
    ("libxfixes" ,libxfixes)
    ("libxxf86vm" ,libxxf86vm)
    ("zstd:lib" ,zstd "lib")
    ("libnsl" ,libnsl)
    ("libpng" ,libpng)
    ("icu4c" ,icu4c)
    ("llvm" ,llvm-for-mesa)
    ("lsof" ,lsof)
    ("mesa" ,mesa)
    ("nspr" ,nspr)
    ("nss-certs" ,nss-certs)
    ("nss" ,nss)
    ("pango" ,pango)
    ("pciutils" ,pciutils)
    ("procps" ,procps)
    ("openssl" ,openssl-1.1)
    ("sed" ,sed)
    ("sdl2" ,sdl2)
    ("tar" ,tar)
    ("usbutils" ,usbutils)
    ("util-linux" ,util-linux)
    ("vulkan-loader" ,vulkan-loader)
    ("libxshmfence" ,libxshmfence)
    ("cups" ,cups)
    ("wayland" ,wayland)
    ("libxcursor" ,libxcursor)
    ("libxrandr" ,libxrandr)
    ("libxi" ,libxi)
    ("xdg-user-dirs" ,xdg-user-dirs)
    ("flatpak-xdg-utils" ,flatpak-xdg-utils)
    ("xz" ,xz)
    ("zenity" ,zenity)
    ("zlib" ,zlib)
    ("alsa-lib" ,alsa-lib)
    ("alsa-plugins:pulseaudio" ,alsa-plugins "pulseaudio")
    ("font-dejavu" ,font-dejavu)
    ("font-liberation" ,font-liberation)
    ("imgui" ,imgui-1.86)
    ("mangohud" ,mangohud)
    ("openal" ,openal)
    ("pulseaudio" ,pulseaudio)
    ("python" ,python)
    ("spdlog" ,spdlog)))

(define bolt-launcher-ld.so.conf
  (packages->ld.so.conf (list (fhs-union `(,@bolt-launcher-libs ,@fhs-min-libs)
                                         #:name "fhs-union-64"))))

(define bolt-launcher-ld.so.cache
  (ld.so.conf->ld.so.cache bolt-launcher-ld.so.conf))

(define-public bolt-launcher-container
  (nonguix-container (name "bolt-launcher")
                     (wrap-package bolt-launcher-client)
                     (run "/bin/bolt")
                     (ld.so.conf bolt-launcher-ld.so.conf)
                     (ld.so.cache bolt-launcher-ld.so.cache)
                     (union64 (fhs-union `(,@bolt-launcher-libs ,@fhs-min-libs)
                                         #:name "fhs-union-64"))
                     (link-files '("share/applications/bolt-launcher.desktop"))
                     (description (package-description bolt-launcher-client))))

(define-public bolt-launcher
  (nonguix-container->package bolt-launcher-container))

bolt-launcher