(define-module (gunit packages ghidra)
  #:use-module ((guix licenses)
                #:prefix license:)
  #:use-module (gnu packages admin)
  #:use-module (gnu packages algebra)
  #:use-module (gnu packages assembly)
  #:use-module (gnu packages astronomy)
  #:use-module (gnu packages audio)
  #:use-module (gnu packages autotools)
  #:use-module (gnu packages avahi)
  #:use-module (gnu packages backup)
  #:use-module (gnu packages base)
  #:use-module (gnu packages bash)
  #:use-module (gnu packages boost)
  #:use-module (gnu packages check)
  #:use-module (gnu packages chromium)
  #:use-module (gnu packages cmake)
  #:use-module (gnu packages commencement)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages cups)
  #:use-module (gnu packages curl)
  #:use-module (gnu packages databases)
  #:use-module (gnu packages documentation)
  #:use-module (gnu packages elf)
  #:use-module (gnu packages engineering)
  #:use-module (gnu packages file)
  #:use-module (gnu packages fltk)
  #:use-module (gnu packages fonts)
  #:use-module (gnu packages fontutils)
  #:use-module (gnu packages freedesktop)
  #:use-module (gnu packages gawk)
  #:use-module (gnu packages gcc)
  #:use-module (gnu packages gd)
  #:use-module (gnu packages geo)
  #:use-module (gnu packages gettext)
  #:use-module (gnu packages ghostscript)
  #:use-module (gnu packages gl)
  #:use-module (gnu packages gdb)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages gnome)
  #:use-module (gnu packages golang)
  #:use-module (gnu packages golang-xyz)
  #:use-module (gnu packages gps)
  #:use-module (gnu packages graphics)
  #:use-module (gnu packages graphviz)
  #:use-module (gnu packages gstreamer)
  #:use-module (gnu packages gtk)
  #:use-module (gnu packages icu4c)
  #:use-module (gnu packages image)
  #:use-module (gnu packages image-processing)
  #:use-module (gnu packages java)
  #:use-module (gnu packages javascript)
  #:use-module (gnu packages jemalloc)
  #:use-module (gnu packages libbsd)
  #:use-module (gnu packages libedit)
  #:use-module (gnu packages libusb)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages llvm)
  #:use-module (gnu packages logging)
  #:use-module (gnu packages lsof)
  #:use-module (gnu packages lua)
  #:use-module (gnu packages man)
  #:use-module (gnu packages maths)
  #:use-module (gnu packages mp3)
  #:use-module (gnu packages multiprecision)
  #:use-module (gnu packages ncurses)
  #:use-module (gnu packages networking)
  #:use-module (gnu packages nss)
  #:use-module (gnu packages onc-rpc)
  #:use-module (gnu packages openstack)
  #:use-module (gnu packages pciutils)
  #:use-module (gnu packages perl)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages popt)
  #:use-module (gnu packages pretty-print)
  #:use-module (gnu packages protobuf)
  #:use-module (gnu packages pulseaudio)
  #:use-module (gnu packages python)
  #:use-module (gnu packages python-build)
  #:use-module (gnu packages python-check)
  #:use-module (gnu packages python-science)
  #:use-module (gnu packages python-web)
  #:use-module (gnu packages python-xyz)
  #:use-module (gnu packages qt)
  #:use-module (gnu packages readline)
  #:use-module (gnu packages ruby)
  #:use-module (gnu packages sdl)
  #:use-module (gnu packages serialization)
  #:use-module (gnu packages sphinx)
  #:use-module (gnu packages sqlite)
  #:use-module (gnu packages swig)
  #:use-module (gnu packages tcl)
  #:use-module (gnu packages tex)
  #:use-module (gnu packages texinfo)
  #:use-module (gnu packages tls)
  #:use-module (gnu packages toolkits)
  #:use-module (gnu packages version-control)
  #:use-module (gnu packages video)
  #:use-module (gnu packages vulkan)
  #:use-module (gnu packages web)
  #:use-module (gnu packages wget)
  #:use-module (gnu packages wxwidgets)
  #:use-module (gnu packages xdisorg)
  #:use-module (gnu packages xiph)
  #:use-module (gnu packages xml)
  #:use-module (gnu packages xorg)
  #:use-module (gnu packages)
  #:use-module (guix base16)
  #:use-module (guix build gnu-build-system)
  #:use-module (guix build utils)
  #:use-module (guix build-system copy)
  #:use-module (guix build-system glib-or-gtk)
  #:use-module (guix build-system gnu)
  #:use-module (guix build-system go)
  #:use-module (guix build-system pyproject)
  #:use-module (guix build-system python)
  #:use-module (guix build-system qt)
  #:use-module (guix download)
  #:use-module (guix gexp)
  #:use-module (guix git-download)
  #:use-module (guix packages)
  #:use-module (guix utils)
  #:use-module (nongnu packages chromium)
  #:use-module (nongnu packages editors)
  #:use-module (nonguix build-system binary)
  #:use-module (nonguix multiarch-container)
  #:use-module (nonguix utils))

(define-public ghidra-bin
  (package
    (name "ghidra-bin")
    (version "12.0.1")
    (source
     (origin
       (method url-fetch)
       (uri (string-append
             "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_"
             version "_build/ghidra_" version "_PUBLIC_20260114.zip"))
       (sha256
        (base32 "0h8ggy67h049czkwcqmc7fz7gas03yxz228y9pgphfjzjj82kgc5"))))
    (build-system copy-build-system)
    (arguments
     (list
      #:phases
      #~(modify-phases %standard-phases
          (add-after 'install 'wrap-ghidra
            (lambda _
              (let* ((out #$output)
                     (orig (string-append out "/support/launch.sh.orig"))
                     (wrap (string-append out "/support/launch.sh")))
                (rename-file (string-append out "/support/launch.sh") orig)
                (call-with-output-file wrap
                  (lambda (port)
                    (format port "#!~a\n"
                            (which "bash"))
                    (format port "export _JAVA_AWT_WM_NONREPARENTING=1\n")
                    (format port "orig=\"~a\"\n" orig)
                    (format port "if [ $# -eq 0 ]; then\n")
                    (format port
                     "  exec \"$orig\" fg jdk Ghidra \"\" \"\" ghidra.GhidraRun")
                    (format port "\nelse\n")
                    (format port "  exec \"$orig\" \"$@\"\n")
                    (format port "fi\n")))
                (chmod wrap #o755)))))))
    (inputs (list gcc gcc-toolchain python gnu-make unzip))
    (native-inputs (list gcc-toolchain git unzip wget))
    (synopsis "A software reverse engineering suite")
    (home-page "https://ghidra-sre.org/")
    (description
     "A software reverse engineering (SRE) suite of tools developed by NSA's Research Directorate in support of the Cybersecurity mission")
    (license license:agpl3)))

(define-public ghidra-libs
  `(("at-spi2-core" ,at-spi2-core)
    ("bash" ,bash)
    ("cairo" ,cairo)
    ("coreutils" ,coreutils)
    ("diffutils" ,diffutils)
    ("dbus-glib" ,dbus-glib)
    ("elfutils" ,elfutils)
    ("eudev" ,eudev)
    ("expat" ,expat)
    ("fontconfig" ,fontconfig)
    ("file" ,file)
    ("find" ,findutils)
    ("fmt" ,fmt)
    ("font-google-noto" ,font-google-noto)
    ("font-google-noto-emoji" ,font-google-noto-emoji)
    ("font-google-noto-sans-cjk" ,font-google-noto-sans-cjk)
    ("font-google-noto-serif-cjk" ,font-google-noto-serif-cjk)
    ("freetype" ,freetype)
    ("bzip2" ,bzip2)
    ("curl" ,curl)
    ("libxtst" ,libxtst)
    ("libxscrnsaver" ,libxscrnsaver)
    ("gawk" ,gawk)
    ("gdk-pixbuf" ,gdk-pixbuf)
    ("gcc:lib" ,gcc-14 "lib")
    ("openjdk:jdk" ,openjdk "jdk")
    ("gdb" ,gdb)
    ("glib" ,glib)
    ("glibc" ,glibc)
    ("grep" ,grep)
    ("gtk+" ,gtk+)
    ("gtk" ,gtk+-2)
    ("libbsd" ,libbsd)
    ("libcap" ,libcap)
    ("libdrm" ,libdrm)
    ("libglvnd" ,libglvnd)
    ("libusb" ,libusb)
    ("libsm" ,libsm)
    ("libxcb" ,libxcb)
    ("libxcomposite" ,libxcomposite)
    ("libxext" ,libxext)
    ("libxkbcommon" ,libxkbcommon)
    ("libva" ,libva)
    ("libvdpau" ,libvdpau)
    ("libvdpau-va-gl" ,libvdpau-va-gl)
    ("libx11" ,libx11)
    ("libxdamage" ,libxdamage)
    ("libxfixes" ,libxfixes)
    ("libxxf86vm" ,libxxf86vm)
    ("zstd:lib" ,zstd "lib")
    ("libnsl" ,libnsl)
    ("libpng" ,libpng)
    ("icu4c" ,icu4c)
    ("llvm" ,llvm-for-mesa)
    ("lsof" ,lsof)
    ("mesa" ,mesa)
    ("nspr" ,nspr)
    ("nss-certs" ,nss-certs)
    ("nss" ,nss)
    ("pango" ,pango)
    ("pciutils" ,pciutils)
    ("procps" ,procps)
    ("openssl" ,openssl-1.1)
    ("sed" ,sed)
    ("sdl2" ,sdl2)
    ("tar" ,tar)
    ("usbutils" ,usbutils)
    ("util-linux" ,util-linux)
    ("vulkan-loader" ,vulkan-loader)
    ("libxshmfence" ,libxshmfence)
    ("cups" ,cups)
    ("wayland" ,wayland)
    ("libxcursor" ,libxcursor)
    ("libxrandr" ,libxrandr)
    ("libxi" ,libxi)
    ("xdg-user-dirs" ,xdg-user-dirs)
    ("flatpak-xdg-utils" ,flatpak-xdg-utils)
    ("xz" ,xz)
    ("zenity" ,zenity)
    ("zlib" ,zlib)
    ("alsa-lib" ,alsa-lib)
    ("alsa-plugins:pulseaudio" ,alsa-plugins "pulseaudio")
    ("font-dejavu" ,font-dejavu)
    ("font-liberation" ,font-liberation)
    ("imgui" ,imgui)
    ("mangohud" ,mangohud)
    ("openal" ,openal)
    ("pulseaudio" ,pulseaudio)
    ("python" ,python)
    ("spdlog" ,spdlog)))

(define ghidra-ld.so.conf
  (packages->ld.so.conf (list (fhs-union `(,@ghidra-libs ,@fhs-min-libs)
                                         #:name "fhs-union-64"))))

(define ghidra-ld.so.cache
  (ld.so.conf->ld.so.cache ghidra-ld.so.conf))

(define-public ghidra-container
  (nonguix-container (name "ghidra")
                     (wrap-package ghidra-bin)
                     (run "/support/launch.sh")
                     (ld.so.conf ghidra-ld.so.conf)
                     (ld.so.cache ghidra-ld.so.cache)
                     (union64 (fhs-union `(,@ghidra-libs ,@fhs-min-libs)
                                         #:name "fhs-union-64"))
                     (link-files '("share/applications/ghidra.desktop"))
                     (description (package-description ghidra-bin))))

(define-public ghidra
  (nonguix-container->package ghidra-container))

ghidra